version: '3.2'
services:
  dev:
    hostname: 'tredev'
    image: 'tredev'
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.8"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        TERRAFORM_VERSION: "1.0.5"
        # We need to sync the docker group id within WSL and the container. This will
        # default to 1001. If yours is set to something different,
        # add the following line to your .bash_profile on the host
        # export DOCKER_GROUP_ID=$(getent group docker | awk -F ":" '{ print $3 }')
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-1001}
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
    - type: bind
      source: ..
      target: /workspaces/tre/
      consistency: cached
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
